services:
  app:
    healthcheck:
      test: curl --fail http://localhost:8080/api/v1/auth/health || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
    build:
      dockerfile: ./Dockerfile
      context: ./
    depends_on:
      storage:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - HTTP_CONFIG_PATH=config/docker.yml
  storage:
    healthcheck:
      test: pg_isready -U postgres -d postgres
    image: postgres:15.4
    container_name: storage
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./schema/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - 5432:5432
  tests:
    build:
      dockerfile: ./tests/Dockerfile
      context: ./
    depends_on:
       app:
         condition: service_healthy
    environment:
       - HTTP_CONFIG_PATH=../config/docker.yml
    profiles:
      - test
    command: ["go", "test", "-v", "./tests/"]