address:
  ":8080"
postgres:
  host: storage
  port: 5432
  user: postgres
  password: password
  db_name: postgres
log:
  level: debug
  format: text
jwt:
  secret:
    "super-secret-key"
  refreshExp:
    80
  accessExp:
    1
smtp:
  host:
    "tests"
  port:
    "2525"
  username:
    "test"
  password:
    "test"